name: Latest docker image

on:
  push
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build, login and push
      run: make build.latest
